[0m12:23:06.578442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071b87d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10719be10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071bbfd0>]}


============================== 12:23:06.582408 | 96693eaa-8318-4b37-b2cb-a2829d620436 ==============================
[0m12:23:06.582408 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:23:06.582895 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/navyasri/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m12:23:06.592075 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/navyasri/.dbt')}
[0m12:23:06.592438 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:23:26.977873 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:23:26.989674 [info ] [MainThread]: 
Your new dbt project "custom_elt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:23:26.990333 [info ] [MainThread]: Setting up your profile.
[0m12:24:52.698574 [error] [MainThread]: Encountered an error:

[0m12:24:52.706397 [error] [MainThread]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/task/init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/task/init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/task/init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/task/init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m12:24:52.755286 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 106.23161, "process_user_time": 0.932517, "process_kernel_time": 0.18097, "process_mem_max_rss": "98975744", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:24:52.756213 [debug] [MainThread]: Command `dbt init` failed at 12:24:52.756090 after 106.23 seconds
[0m12:24:52.756658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071a2450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102885d50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b22c90>]}
[0m12:24:52.757085 [debug] [MainThread]: Flushing usage events
[0m12:24:57.202016 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1116927d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111710650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111710c10>]}


============================== 12:24:57.205851 | c7328d24-f574-4f32-952e-83bafd2dd142 ==============================
[0m12:24:57.205851 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:24:57.206336 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/navyasri/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:25:10.272700 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dbt/include/starter_project
[0m12:25:10.285735 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:25:10.286387 [info ] [MainThread]: Setting up your profile.
[0m12:32:23.043502 [info ] [MainThread]: Profile custom_postgres written to /Users/navyasri/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:32:23.050925 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 445.8993, "process_user_time": 0.927236, "process_kernel_time": 0.169765, "process_mem_max_rss": "102957056", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:32:23.052951 [debug] [MainThread]: Command `dbt init` succeeded at 12:32:23.052667 after 445.90 seconds
[0m12:32:23.054176 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e55e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e55dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d12750>]}
[0m12:32:23.055126 [debug] [MainThread]: Flushing usage events
